Create 2017-4-12-swarm-service-discovery.markdown
play-with-docker/play-with-docker.github.io pull request #22
Opened 2017-04-12 03:56 UTC by ajeetraina

Added a short tutorial on Service Discovery

2017-04-12 04:03 UTC, marcosnils commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +What features are available under Swarm Mode?
There's no marked answer.

2017-04-12 04:03 UTC, marcosnils commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +terms: 2
You're adding two terms but only using one in the whole tutorial.

2017-04-12 04:03 UTC, marcosnils commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +```.term1
Maybe remove extra nodes to avoid confusion in the output?. As the one shown by the tutorial will only have two nodes.

2017-04-12 04:06 UTC, ajeetraina commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +terms: 2
Good catch. Will fix it.

2017-04-12 04:07 UTC, ajeetraina commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +```.term1
Sure. I can go ahead and remove the extra nodes.

2017-04-12 04:07 UTC, ajeetraina commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +What features are available under Swarm Mode?
Oops..I think I missed the answer section. Will add it.

2017-04-12 04:17 UTC, marcosnils commented on _posts/2017-4-12-swarm-service-discovery.markdown
>  xsuyuqj2v254dy09t00w8we0t    node2     Ready   Active
We should remove node2 as well as the swarm has only one leader in this tutorial.

2017-04-12 04:19 UTC, marcosnils commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +$docker network create -d overlay net1
incorrect character here?

2017-04-12 04:19 UTC, marcosnils commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +You should get an output like the following one where the 1 task  of the service are listed.
This sentence needs correction:

`You should get an output like the following one where 1 task of the service is listed`

2017-04-12 05:49 UTC, marcosnils commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +categories: beginner
maybe intermediate?. Swarm concepts are for more advanced docker users usually.

2017-04-12 05:49 UTC, marcosnils commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
The command output should be inside ``` when using `.term1` or it'll be executed in the terminal.

2017-04-12 05:49 UTC, marcosnils commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +NETWORK ID          NAME                DRIVER              SCOPE
Output shouldn't be inside the ```.term1

2017-04-12 05:49 UTC, marcosnils commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +ID            NAME                     MODE        REPLICAS  IMAGE
Output shouldn't be inside ```.term1.

2017-04-12 05:49 UTC, marcosnils commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +ID                  NAME                IMAGE               NODE                DESIRED STATE
Output shouldn't be inside ```.term1

2017-04-12 05:49 UTC, marcosnils commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +ID                  NAME                MODE                REPLICAS            IMAGE
Output shouldn't be inside ```.term1.

2017-04-12 05:49 UTC, marcosnils commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS
Output shouldn't be inside ```.term1.

2017-04-12 05:49 UTC, marcosnils commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +docker container exec -it 31b ping wordpressdb
Output shouldn't be inside ```.term1.

2017-04-12 06:06 UTC, ajeetraina commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +categories: beginner
Yeah, was thinking over it. Will keep it intermediate.

2017-04-12 06:07 UTC, ajeetraina commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
Sure.

2017-04-12 16:44 UTC, marcosnils requested changes
@ajeetraina seems like you're confused about how to use

\`\`\`.term1
\`\`\`
and  just plain

\`\`\`
\`\`\`

the first one should be used to put only commands that will be executed in the terminal when clicking them. The second one is just for outputs.

There are several places in the article where \`\`\`.term1 can be used and you're using \`\`\` instead.

2017-04-12 16:44 UTC, marcosnils commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +xsuyuqj2v254dy09t00w8we0t    node2     Ready   Active
`node2` needs to be removed. This tutorial doesn't use 2 nodes.

2017-04-12 19:14 UTC, marcosnils commented on _posts/2017-4-12-swarm-service-discovery.markdown
> +This node becomes a master node. The output displays a command to add a worker node to this swarm as shown below:
Is it relevant to the content of the article how to add a worker?. It's not mentioned anywhere else.

2017-04-13 06:10 UTC, ajeetraina commented
Hi,

As I am talking about Swarm Mode,  I wanted to demonstrate with at least 2
node cluster. As I want to demo that a container sitting on master node can
reach out to other container running the service by service name. That's
the whole purpose.

I added the instructions earlier,  will go ahead and add as an example.

Ajeet

+From the output above, copy the join command (*watch out for newlines*),
add the new instance and paste the command.This should join the new node to
the swarm mode and it becomes a worker node

On 13-Apr-2017 12:44 AM, "Marcos Nils" <notifications@github.com> wrote:

> *@marcosnils* commented on this pull request.
> ------------------------------
>
> In _posts/2017-4-12-swarm-service-discovery.markdown
> <https://github.com/franela/franela.github.io/pull/22#discussion_r111234484>
> :
>
> > +
> +## The application
> +
> +WordPress is an open-source content management system (CMS) based on PHP and MySQL.
> +It is a very simple containers application often used for demo purposes during meetup and conferences.
> +
> +
> +## Init your swarm
> +
> +Let's create a Docker Swarm first. Open up the first instance and initiate Swarm mode cluster.
> +
> +```.term1
> +docker swarm init --advertise-addr $(hostname -i)
> +```
> +
> +This node becomes a master node. The output displays a command to add a worker node to this swarm as shown below:
>
> Is it relevant to the content of the article how to add a worker?. It's
> not mentioned anywhere else.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/franela/franela.github.io/pull/22#pullrequestreview-32466015>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AATIiEdyu598U8jdrASp2u7DkLVY9_OEks5rvSKXgaJpZM4M67JA>
> .
>

2017-04-13 06:19 UTC, marcosnils commented
> As I am talking about Swarm Mode,  I wanted to demonstrate with at least 2
> node cluster. As I want to demo that a container sitting on master node can
> reach out to other container running the service by service name. That's
> the whole purpose.

Ok, makes sense. If that is the intention then maybe we can update the tutorial to use two terms and show how the services are moved across the different nodes. As it is currently, only one swarm node is being used.

2017-04-14 04:58 UTC, merged